name:                hrl
version:             0.1.0.0
github:              "siddharthverma314/hrl"
license:             BSD3
author:              "Siddharth Verma"
maintainer:          "siddharthverma314@gmail.com"
copyright:           "2020 Siddharth Verma"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/siddharthverma314/hrl#readme>

dependencies:
- base >= 4.7 && < 5
- hasktorch

library:
  source-dirs: src

executables:
  hrl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hrl

tests:
  hrl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hrl
